version: '3.5'
services:

  # Application Container
  docmaps-app:
    container_name: docmaps-app
    image: docmaps-app
    build:
      context: ./
      dockerfile: docker/application/Dockerfile
      args:
        - XDEBUG_REMOTE_ENABLE=${XDEBUG_REMOTE_ENABLE}
        - XDEBUG_REMOTE_AUTOSTART=${XDEBUG_REMOTE_AUTOSTART}
        - XDEBUG_PROFILER_ENABLE=${XDEBUG_PROFILER_ENABLE}
    working_dir: /var/www
    ports:
      - 9030:9000
    networks:
      - docmaps
    volumes:
      - ./:/var/www
    depends_on:
      - docmaps-db
    environment:
      - "DB_DATABASE=homestead"
      - "DB_USERNAME=homestead"
      - "DB_HOST=docmaps-db"
      - "DB_PASSWORD=Trombone500"
      - "REDIS_HOST=docmaps-redis"
      - "APP_URL=http://localhost:8087"
      - "CACHE_DRIVER=redis"
      - "XDEBUG_CONFIG=remote_host=host.docker.internal"
      - "PHP_IDE_CONFIG=serverName=docmaps"

  # Web Container
  docmaps-web:
    container_name: docmaps-web
    image: docmaps-web
    build:
      context: ./
      dockerfile: docker/web/Dockerfile
    working_dir: /var/www
    depends_on:
      - docmaps-app
    networks:
      - docmaps
    volumes:
      - ./public:/var/www/public
    ports:
      - 8087:80

  # Database Container
  docmaps-db:
    container_name: docmaps-db
    networks:
      - docmaps
    image: mysql:5.7
    volumes:
      - docmaps-db:/var/lib/mysql2
    environment:
      - "MYSQL_ROOT_PASSWORD=Trombone500"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=Trombone500"
      - "MYSQL_DATABASE=homestead"
    ports:
      - 33082:3306

  # Redis Container
  docmaps-redis:
    container_name: docmaps-redis
    networks:
      - docmaps
    image: redis:latest
    ports:
      - 6385:6379

volumes:
  docmaps-db:

networks:
  docmaps:
    name: docmaps
